export const countriesTimezones = [
    { country: 'Afghanistan', timezone: 'Asia/Kabul' },
    { country: 'Albania', timezone: 'Europe/Tirane' },
    { country: 'Algeria', timezone: 'Africa/Algiers' },
    { country: 'Andorra', timezone: 'Europe/Andorra' },
    { country: 'Angola', timezone: 'Africa/Luanda' },
    { country: 'Argentina', timezone: 'America/Argentina/Buenos_Aires' },
    { country: 'Armenia', timezone: 'Asia/Yerevan' },
    { country: 'Australia', timezone: 'Australia/Sydney' },
    { country: 'Austria', timezone: 'Europe/Vienna' },
    { country: 'Azerbaijan', timezone: 'Asia/Baku' },
    { country: 'Bangladesh', timezone: 'Asia/Dhaka' },
    { country: 'Belgium', timezone: 'Europe/Brussels' },
    { country: 'Brazil', timezone: 'America/Sao_Paulo' },
    { country: 'Canada', timezone: 'America/Toronto' },
    { country: 'Chile', timezone: 'America/Santiago' },
    { country: 'China', timezone: 'Asia/Shanghai' },
    { country: 'Colombia', timezone: 'America/Bogota' },
    { country: 'Denmark', timezone: 'Europe/Copenhagen' },
    { country: 'Egypt', timezone: 'Africa/Cairo' },
    { country: 'Finland', timezone: 'Europe/Helsinki' },
    { country: 'France', timezone: 'Europe/Paris' },
    { country: 'Germany', timezone: 'Europe/Berlin' },
    { country: 'Greece', timezone: 'Europe/Athens' },
    { country: 'Hong Kong', timezone: 'Asia/Hong_Kong' },
    { country: 'India', timezone: 'Asia/Kolkata' },
    { country: 'Indonesia', timezone: 'Asia/Jakarta' },
    { country: 'Iran', timezone: 'Asia/Tehran' },
    { country: 'Iraq', timezone: 'Asia/Baghdad' },
    { country: 'Ireland', timezone: 'Europe/Dublin' },
    { country: 'Israel', timezone: 'Asia/Jerusalem' },
    { country: 'Italy', timezone: 'Europe/Rome' },
    { country: 'Japan', timezone: 'Asia/Tokyo' },
    { country: 'Kazakhstan', timezone: 'Asia/Almaty' },
    { country: 'Kenya', timezone: 'Africa/Nairobi' },
    { country: 'Malaysia', timezone: 'Asia/Kuala_Lumpur' },
    { country: 'Mexico', timezone: 'America/Mexico_City' },
    { country: 'Netherlands', timezone: 'Europe/Amsterdam' },
    { country: 'New Zealand', timezone: 'Pacific/Auckland' },
    { country: 'Nigeria', timezone: 'Africa/Lagos' },
    { country: 'Norway', timezone: 'Europe/Oslo' },
    { country: 'Pakistan', timezone: 'Asia/Karachi' },
    { country: 'Philippines', timezone: 'Asia/Manila' },
    { country: 'Poland', timezone: 'Europe/Warsaw' },
    { country: 'Portugal', timezone: 'Europe/Lisbon' },
    { country: 'Russia', timezone: 'Europe/Moscow' },
    { country: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
    { country: 'Singapore', timezone: 'Asia/Singapore' },
    { country: 'South Africa', timezone: 'Africa/Johannesburg' },
    { country: 'South Korea', timezone: 'Asia/Seoul' },
    { country: 'Spain', timezone: 'Europe/Madrid' },
    { country: 'Sweden', timezone: 'Europe/Stockholm' },
    { country: 'Switzerland', timezone: 'Europe/Zurich' },
    { country: 'Thailand', timezone: 'Asia/Bangkok' },
    { country: 'Turkey', timezone: 'Europe/Istanbul' },
    { country: 'Ukraine', timezone: 'Europe/Kiev' },
    { country: 'United Arab Emirates', timezone: 'Asia/Dubai' },
    { country: 'United Kingdom', timezone: 'Europe/London' },
    { country: 'United States', timezone: 'America/New_York' },
    { country: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh' },
    // Add more countries and their primary timezones as needed
];
